version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata_tochka:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    depends_on:
      - backend

  redis:
    image: redis:7.0.11-alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pg_admin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:  
  #     - "8888:80"
  #   restart: always

volumes:
  pgdata_tochka:
